run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - goimports
    - revive
    - misspell
    - unconvert
    - prealloc
    - bodyclose

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: package-comments
      - name: exported
      - name: if-return

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\\.go
      linters: [errcheck, unused]
